---
kind: pipeline
type: docker
name: default

workspace:
  path: /drone/src

volumes:
  - name: cache
    temp: { }
  - name: dist
    temp: { }

environment:
  GOCACHE: /cache/go/build
  GOMODCACHE: /cache/go/download
  NPM_CONFIG_CACHE: /cache/npm/cache

steps:
  - name: go deps
    image: golang:1.17.3-alpine3.14
    volumes:
      - name: cache
        path: /cache
    commands:
      - apk --no-cache add git
      - go get -t -d -v ./...
      - go build all

  - name: node deps
    image: node:14.18.1
    volumes:
      - name: cache
        path: /cache
    commands:
      - cd frontend
      - yarn install --non-interactive

  - name: build wgrest server
    image: golang:1.17.3-alpine3.14
    privileged: true
    volumes:
      - name: cache
        path: /cache
      - name: dist
        path: /drone/src/dist
    commands:
      - export VERSION=${DRONE_TAG:-${DRONE_COMMIT:0:7}}
      - apk --no-cache add build-base
      - make build
    depends_on:
      - go deps

  - name: build wgrest ui
    image: node:14.18.1
    privileged: true
    volumes:
      - name: cache
        path: /cache
      - name: dist
        path: /drone/src/dist
    commands:
      - cd frontend
      - yarn build --dest ../dist/public
    depends_on:
      - node deps

  - name: build
    image: alpine:3.14.3
    privileged: true
    volumes:
      - name: dist
        path: /drone/src/dist
    commands:
      - export VERSION=${DRONE_TAG:-${DRONE_COMMIT:0:7}}
      - apk --no-cache add nfpm
      - nfpm pkg -f packaging/nfpm-amd64.yaml --packager deb --target dist/wgrest_amd64.deb
      - nfpm pkg -f packaging/nfpm-arm64.yaml --packager deb --target dist/wgrest_arm64.deb
      - tar -czvf dist/webapp.tar.gz -C dist/ public
      - rm -rf dist/public
    depends_on:
      - build wgrest server
      - build wgrest ui

  - name: github release
    image: plugins/github-release
    volumes:
      - name: dist
        path: /drone/src/dist
    settings:
      api_key:
        from_secret: github_token
      files: dist/*
      checksum:
        - md5
        - sha1
    depends_on:
      - build
    when:
      event:
        - tag

trigger:
  event:
    - push
    - tag