/* tslint:disable */
/* eslint-disable */
/**
 * WireGuard RESTful API
 * Manage WireGuard VPN tunnels by RESTful manner.  Supported features:    * Manage device: create, update, and delete wireguard interface   * Manage device's ip addresses: attache or detach ip addresses to the netowrk interface   * Manage device's peers: create, update, and delete peers   * Peer's QR code, for use in WireGuard & ForestVPN client  ForestVPN client may be used as alternative client with enabled P2P technology over WireGuard tunnelling. Read more on https://forestvpn.com/ 
 *
 * OpenAPI spec version: 1.0
 * Contact: support@forestvpn.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * Information about wireguard device.
 * @export
 * @interface Device
 */
export interface Device {
    /**
     * WireGuard device name. Usually it is network interface name
     * @type {string}
     * @memberof Device
     */
    name: any;
    /**
     * WireGuard device listen port.
     * @type {number}
     * @memberof Device
     */
    listenPort: any;
    /**
     * WireGuard device public key encoded by base64.
     * @type {string}
     * @memberof Device
     */
    publicKey: any;
    /**
     * WireGuard device firewall mark.
     * @type {number}
     * @memberof Device
     */
    firewallMark: any;
    /**
     * IPv4 or IPv6 addresses in CIDR notation
     * @type {Array&lt;string&gt;}
     * @memberof Device
     */
    networks: any;
    /**
     * WireGuard device's peers count
     * @type {number}
     * @memberof Device
     */
    peersCount: any;
    /**
     * WireGuard device's peers total receive bytes
     * @type {number}
     * @memberof Device
     */
    totalReceiveBytes: any;
    /**
     * WireGuard device's peers total transmit bytes
     * @type {number}
     * @memberof Device
     */
    totalTransmitBytes: any;
}
