/* tslint:disable */
/* eslint-disable */
/**
 * WireGuard RESTful API
 * Manage WireGuard VPN tunnels by RESTful manner.  Supported features:    * Manage device: create, update, and delete wireguard interface   * Manage device's ip addresses: attache or detach ip addresses to the netowrk interface   * Manage device's peers: create, update, and delete peers   * Peer's QR code, for use in WireGuard & ForestVPN client  ForestVPN client may be used as alternative client with enabled P2P technology over WireGuard tunnelling. Read more on https://forestvpn.com/ 
 *
 * OpenAPI spec version: 1.0
 * Contact: support@forestvpn.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface ModelError
 */
export interface ModelError {
    /**
     * Error code
     * @type {string}
     * @memberof ModelError
     */
    code: any;
    /**
     * Error's short description
     * @type {string}
     * @memberof ModelError
     */
    message: any;
    /**
     * Error's detail description
     * @type {string}
     * @memberof ModelError
     */
    detail?: any;
}
