/* tslint:disable */
/* eslint-disable */
/**
 * WireGuard RESTful API
 * Manage WireGuard VPN tunnels by RESTful manner.  Supported features:    * Manage device: create, update, and delete wireguard interface   * Manage device's ip addresses: attache or detach ip addresses to the netowrk interface   * Manage device's peers: create, update, and delete peers   * Peer's QR code, for use in WireGuard & ForestVPN client  ForestVPN client may be used as alternative client with enabled P2P technology over WireGuard tunnelling. Read more on https://forestvpn.com/ 
 *
 * OpenAPI spec version: 1.0
 * Contact: support@forestvpn.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * Information about wireguard peer.
 * @export
 * @interface Peer
 */
export interface Peer {
    /**
     * Base64 encoded public key
     * @type {string}
     * @memberof Peer
     */
    publicKey: any;
    /**
     * URL safe base64 encoded public key. It is usefull to use in peers api endpoint.
     * @type {string}
     * @memberof Peer
     */
    urlSafePublicKey: any;
    /**
     * Base64 encoded preshared key
     * @type {string}
     * @memberof Peer
     */
    presharedKey?: any;
    /**
     * Peer's allowed ips, it might be any of IPv4 or IPv6 addresses in CIDR notation
     * @type {Array&lt;string&gt;}
     * @memberof Peer
     */
    allowedIps: any;
    /**
     * Peer's last handshake time formated in RFC3339
     * @type {Date}
     * @memberof Peer
     */
    lastHandshakeTime: any;
    /**
     * Peer's persistend keepalive interval in
     * @type {string}
     * @memberof Peer
     */
    persistentKeepaliveInterval: any;
    /**
     * Peer's endpoint in host:port format
     * @type {string}
     * @memberof Peer
     */
    endpoint: any;
    /**
     * Peer's receive bytes
     * @type {number}
     * @memberof Peer
     */
    receiveBytes: any;
    /**
     * Peer's transmit bytes
     * @type {number}
     * @memberof Peer
     */
    transmitBytes: any;
}
