// Code generated by go-swagger; DO NOT EDIT.

/*
Package restapi WireGuard RESTful API
Manage WireGuard VPN tunnels by RESTful manner


    Schemes:
      http
      https
    Host: localhost
    BasePath: /
    Version: v1.0

    Consumes:
    - application/json

    Produces:
    - application/json

swagger:meta
*/
package restapi
