// Code generated by go-swagger; DO NOT EDIT.

package wireguard

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/suquant/wgrest/models"
)

// DeviceListOKCode is the HTTP code returned for type DeviceListOK
const DeviceListOKCode int = 200

/*DeviceListOK ok

swagger:response deviceListOK
*/
type DeviceListOK struct {

	/*
	  In: Body
	*/
	Payload []*models.WireguardDevice `json:"body,omitempty"`
}

// NewDeviceListOK creates DeviceListOK with default headers values
func NewDeviceListOK() *DeviceListOK {

	return &DeviceListOK{}
}

// WithPayload adds the payload to the device list o k response
func (o *DeviceListOK) WithPayload(payload []*models.WireguardDevice) *DeviceListOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the device list o k response
func (o *DeviceListOK) SetPayload(payload []*models.WireguardDevice) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeviceListOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		// return empty array
		payload = make([]*models.WireguardDevice, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

/*DeviceListDefault error

swagger:response deviceListDefault
*/
type DeviceListDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewDeviceListDefault creates DeviceListDefault with default headers values
func NewDeviceListDefault(code int) *DeviceListDefault {
	if code <= 0 {
		code = 500
	}

	return &DeviceListDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the device list default response
func (o *DeviceListDefault) WithStatusCode(code int) *DeviceListDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the device list default response
func (o *DeviceListDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the device list default response
func (o *DeviceListDefault) WithPayload(payload *models.Error) *DeviceListDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the device list default response
func (o *DeviceListDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeviceListDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
