// Code generated by go-swagger; DO NOT EDIT.

package wireguard

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// DeviceCreateHandlerFunc turns a function with the right signature into a device create handler
type DeviceCreateHandlerFunc func(DeviceCreateParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn DeviceCreateHandlerFunc) Handle(params DeviceCreateParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// DeviceCreateHandler interface for that can handle valid device create params
type DeviceCreateHandler interface {
	Handle(DeviceCreateParams, interface{}) middleware.Responder
}

// NewDeviceCreate creates a new http.Handler for the device create operation
func NewDeviceCreate(ctx *middleware.Context, handler DeviceCreateHandler) *DeviceCreate {
	return &DeviceCreate{Context: ctx, Handler: handler}
}

/*DeviceCreate swagger:route POST /devices/ wireguard deviceCreate

create new wireguard device

*/
type DeviceCreate struct {
	Context *middleware.Context
	Handler DeviceCreateHandler
}

func (o *DeviceCreate) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewDeviceCreateParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
