// Code generated by go-swagger; DO NOT EDIT.

package wireguard

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/suquant/wgrest/models"
)

// DeviceDeleteNoContentCode is the HTTP code returned for type DeviceDeleteNoContent
const DeviceDeleteNoContentCode int = 204

/*DeviceDeleteNoContent no content

swagger:response deviceDeleteNoContent
*/
type DeviceDeleteNoContent struct {
}

// NewDeviceDeleteNoContent creates DeviceDeleteNoContent with default headers values
func NewDeviceDeleteNoContent() *DeviceDeleteNoContent {

	return &DeviceDeleteNoContent{}
}

// WriteResponse to the client
func (o *DeviceDeleteNoContent) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(204)
}

// DeviceDeleteNotFoundCode is the HTTP code returned for type DeviceDeleteNotFound
const DeviceDeleteNotFoundCode int = 404

/*DeviceDeleteNotFound not found

swagger:response deviceDeleteNotFound
*/
type DeviceDeleteNotFound struct {
}

// NewDeviceDeleteNotFound creates DeviceDeleteNotFound with default headers values
func NewDeviceDeleteNotFound() *DeviceDeleteNotFound {

	return &DeviceDeleteNotFound{}
}

// WriteResponse to the client
func (o *DeviceDeleteNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}

/*DeviceDeleteDefault error

swagger:response deviceDeleteDefault
*/
type DeviceDeleteDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewDeviceDeleteDefault creates DeviceDeleteDefault with default headers values
func NewDeviceDeleteDefault(code int) *DeviceDeleteDefault {
	if code <= 0 {
		code = 500
	}

	return &DeviceDeleteDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the device delete default response
func (o *DeviceDeleteDefault) WithStatusCode(code int) *DeviceDeleteDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the device delete default response
func (o *DeviceDeleteDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the device delete default response
func (o *DeviceDeleteDefault) WithPayload(payload *models.Error) *DeviceDeleteDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the device delete default response
func (o *DeviceDeleteDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeviceDeleteDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
