// Code generated by go-swagger; DO NOT EDIT.

package wireguard

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/suquant/wgrest/models"
)

// DeviceGetOKCode is the HTTP code returned for type DeviceGetOK
const DeviceGetOKCode int = 200

/*DeviceGetOK ok

swagger:response deviceGetOK
*/
type DeviceGetOK struct {

	/*
	  In: Body
	*/
	Payload *models.WireguardDevice `json:"body,omitempty"`
}

// NewDeviceGetOK creates DeviceGetOK with default headers values
func NewDeviceGetOK() *DeviceGetOK {

	return &DeviceGetOK{}
}

// WithPayload adds the payload to the device get o k response
func (o *DeviceGetOK) WithPayload(payload *models.WireguardDevice) *DeviceGetOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the device get o k response
func (o *DeviceGetOK) SetPayload(payload *models.WireguardDevice) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeviceGetOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// DeviceGetNotFoundCode is the HTTP code returned for type DeviceGetNotFound
const DeviceGetNotFoundCode int = 404

/*DeviceGetNotFound not found

swagger:response deviceGetNotFound
*/
type DeviceGetNotFound struct {
}

// NewDeviceGetNotFound creates DeviceGetNotFound with default headers values
func NewDeviceGetNotFound() *DeviceGetNotFound {

	return &DeviceGetNotFound{}
}

// WriteResponse to the client
func (o *DeviceGetNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}

/*DeviceGetDefault error

swagger:response deviceGetDefault
*/
type DeviceGetDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewDeviceGetDefault creates DeviceGetDefault with default headers values
func NewDeviceGetDefault(code int) *DeviceGetDefault {
	if code <= 0 {
		code = 500
	}

	return &DeviceGetDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the device get default response
func (o *DeviceGetDefault) WithStatusCode(code int) *DeviceGetDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the device get default response
func (o *DeviceGetDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the device get default response
func (o *DeviceGetDefault) WithPayload(payload *models.Error) *DeviceGetDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the device get default response
func (o *DeviceGetDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeviceGetDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
