// Code generated by go-swagger; DO NOT EDIT.

package wireguard

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// DeviceGetHandlerFunc turns a function with the right signature into a device get handler
type DeviceGetHandlerFunc func(DeviceGetParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn DeviceGetHandlerFunc) Handle(params DeviceGetParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// DeviceGetHandler interface for that can handle valid device get params
type DeviceGetHandler interface {
	Handle(DeviceGetParams, interface{}) middleware.Responder
}

// NewDeviceGet creates a new http.Handler for the device get operation
func NewDeviceGet(ctx *middleware.Context, handler DeviceGetHandler) *DeviceGet {
	return &DeviceGet{Context: ctx, Handler: handler}
}

/*DeviceGet swagger:route GET /devices/{dev} wireguard deviceGet

get wireguard device details

*/
type DeviceGet struct {
	Context *middleware.Context
	Handler DeviceGetHandler
}

func (o *DeviceGet) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewDeviceGetParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
