// Code generated by go-swagger; DO NOT EDIT.

package wireguard

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"io"
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"

	models "github.com/suquant/wgrest/models"
)

// NewDeviceCreateParams creates a new DeviceCreateParams object
// no default values defined in spec.
func NewDeviceCreateParams() DeviceCreateParams {

	return DeviceCreateParams{}
}

// DeviceCreateParams contains all the bound params for the device create operation
// typically these are obtained from a http.Request
//
// swagger:parameters DeviceCreate
type DeviceCreateParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*device configuration
	  Required: true
	  In: body
	*/
	Device *models.WireguardDevice
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewDeviceCreateParams() beforehand.
func (o *DeviceCreateParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	if runtime.HasBody(r) {
		defer r.Body.Close()
		var body models.WireguardDevice
		if err := route.Consumer.Consume(r.Body, &body); err != nil {
			if err == io.EOF {
				res = append(res, errors.Required("device", "body"))
			} else {
				res = append(res, errors.NewParseError("device", "body", "", err))
			}
		} else {
			// validate body object
			if err := body.Validate(route.Formats); err != nil {
				res = append(res, err)
			}

			if len(res) == 0 {
				o.Device = &body
			}
		}
	} else {
		res = append(res, errors.Required("device", "body"))
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
