// Code generated by go-swagger; DO NOT EDIT.

package wireguard

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/suquant/wgrest/models"
)

// DeviceCreateCreatedCode is the HTTP code returned for type DeviceCreateCreated
const DeviceCreateCreatedCode int = 201

/*DeviceCreateCreated created

swagger:response deviceCreateCreated
*/
type DeviceCreateCreated struct {
	/*

	 */
	Location string `json:"Location"`
}

// NewDeviceCreateCreated creates DeviceCreateCreated with default headers values
func NewDeviceCreateCreated() *DeviceCreateCreated {

	return &DeviceCreateCreated{}
}

// WithLocation adds the location to the device create created response
func (o *DeviceCreateCreated) WithLocation(location string) *DeviceCreateCreated {
	o.Location = location
	return o
}

// SetLocation sets the location to the device create created response
func (o *DeviceCreateCreated) SetLocation(location string) {
	o.Location = location
}

// WriteResponse to the client
func (o *DeviceCreateCreated) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	// response header Location

	location := o.Location
	if location != "" {
		rw.Header().Set("Location", location)
	}

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(201)
}

/*DeviceCreateDefault error

swagger:response deviceCreateDefault
*/
type DeviceCreateDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewDeviceCreateDefault creates DeviceCreateDefault with default headers values
func NewDeviceCreateDefault(code int) *DeviceCreateDefault {
	if code <= 0 {
		code = 500
	}

	return &DeviceCreateDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the device create default response
func (o *DeviceCreateDefault) WithStatusCode(code int) *DeviceCreateDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the device create default response
func (o *DeviceCreateDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the device create default response
func (o *DeviceCreateDefault) WithPayload(payload *models.Error) *DeviceCreateDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the device create default response
func (o *DeviceCreateDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeviceCreateDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
