// Code generated by go-swagger; DO NOT EDIT.

package wireguard

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// PeerCreateHandlerFunc turns a function with the right signature into a peer create handler
type PeerCreateHandlerFunc func(PeerCreateParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn PeerCreateHandlerFunc) Handle(params PeerCreateParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// PeerCreateHandler interface for that can handle valid peer create params
type PeerCreateHandler interface {
	Handle(PeerCreateParams, interface{}) middleware.Responder
}

// NewPeerCreate creates a new http.Handler for the peer create operation
func NewPeerCreate(ctx *middleware.Context, handler PeerCreateHandler) *PeerCreate {
	return &PeerCreate{Context: ctx, Handler: handler}
}

/*PeerCreate swagger:route POST /devices/{dev}/peers/ wireguard peerCreate

add peer to wireguard device

*/
type PeerCreate struct {
	Context *middleware.Context
	Handler PeerCreateHandler
}

func (o *PeerCreate) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewPeerCreateParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
