// Code generated by go-swagger; DO NOT EDIT.

package wireguard

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/suquant/wgrest/models"
)

// PeerDeleteNoContentCode is the HTTP code returned for type PeerDeleteNoContent
const PeerDeleteNoContentCode int = 204

/*PeerDeleteNoContent no content

swagger:response peerDeleteNoContent
*/
type PeerDeleteNoContent struct {
}

// NewPeerDeleteNoContent creates PeerDeleteNoContent with default headers values
func NewPeerDeleteNoContent() *PeerDeleteNoContent {

	return &PeerDeleteNoContent{}
}

// WriteResponse to the client
func (o *PeerDeleteNoContent) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(204)
}

// PeerDeleteNotFoundCode is the HTTP code returned for type PeerDeleteNotFound
const PeerDeleteNotFoundCode int = 404

/*PeerDeleteNotFound not found

swagger:response peerDeleteNotFound
*/
type PeerDeleteNotFound struct {
}

// NewPeerDeleteNotFound creates PeerDeleteNotFound with default headers values
func NewPeerDeleteNotFound() *PeerDeleteNotFound {

	return &PeerDeleteNotFound{}
}

// WriteResponse to the client
func (o *PeerDeleteNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}

/*PeerDeleteDefault error

swagger:response peerDeleteDefault
*/
type PeerDeleteDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewPeerDeleteDefault creates PeerDeleteDefault with default headers values
func NewPeerDeleteDefault(code int) *PeerDeleteDefault {
	if code <= 0 {
		code = 500
	}

	return &PeerDeleteDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the peer delete default response
func (o *PeerDeleteDefault) WithStatusCode(code int) *PeerDeleteDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the peer delete default response
func (o *PeerDeleteDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the peer delete default response
func (o *PeerDeleteDefault) WithPayload(payload *models.Error) *PeerDeleteDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the peer delete default response
func (o *PeerDeleteDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PeerDeleteDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
