// Code generated by go-swagger; DO NOT EDIT.

package wireguard

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"io"
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/suquant/wgrest/models"
)

// NewPeerCreateParams creates a new PeerCreateParams object
// no default values defined in spec.
func NewPeerCreateParams() PeerCreateParams {

	return PeerCreateParams{}
}

// PeerCreateParams contains all the bound params for the peer create operation
// typically these are obtained from a http.Request
//
// swagger:parameters PeerCreate
type PeerCreateParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*
	  Required: true
	  In: path
	*/
	Dev string
	/*peer configuration
	  Required: true
	  In: body
	*/
	Peer *models.WireguardPeer
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewPeerCreateParams() beforehand.
func (o *PeerCreateParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	rDev, rhkDev, _ := route.Params.GetOK("dev")
	if err := o.bindDev(rDev, rhkDev, route.Formats); err != nil {
		res = append(res, err)
	}

	if runtime.HasBody(r) {
		defer r.Body.Close()
		var body models.WireguardPeer
		if err := route.Consumer.Consume(r.Body, &body); err != nil {
			if err == io.EOF {
				res = append(res, errors.Required("peer", "body"))
			} else {
				res = append(res, errors.NewParseError("peer", "body", "", err))
			}
		} else {
			// validate body object
			if err := body.Validate(route.Formats); err != nil {
				res = append(res, err)
			}

			if len(res) == 0 {
				o.Peer = &body
			}
		}
	} else {
		res = append(res, errors.Required("peer", "body"))
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindDev binds and validates parameter Dev from path.
func (o *PeerCreateParams) bindDev(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route

	o.Dev = raw

	return nil
}
