// Code generated by go-swagger; DO NOT EDIT.

package wireguard

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// PeerDeleteHandlerFunc turns a function with the right signature into a peer delete handler
type PeerDeleteHandlerFunc func(PeerDeleteParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn PeerDeleteHandlerFunc) Handle(params PeerDeleteParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// PeerDeleteHandler interface for that can handle valid peer delete params
type PeerDeleteHandler interface {
	Handle(PeerDeleteParams, interface{}) middleware.Responder
}

// NewPeerDelete creates a new http.Handler for the peer delete operation
func NewPeerDelete(ctx *middleware.Context, handler PeerDeleteHandler) *PeerDelete {
	return &PeerDelete{Context: ctx, Handler: handler}
}

/*PeerDelete swagger:route DELETE /devices/{dev}/peers/{peer_id} wireguard peerDelete

delete wireguard's peer

*/
type PeerDelete struct {
	Context *middleware.Context
	Handler PeerDeleteHandler
}

func (o *PeerDelete) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewPeerDeleteParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
