// Code generated by go-swagger; DO NOT EDIT.

package wireguard

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/suquant/wgrest/models"
)

// PeerCreateCreatedCode is the HTTP code returned for type PeerCreateCreated
const PeerCreateCreatedCode int = 201

/*PeerCreateCreated created

swagger:response peerCreateCreated
*/
type PeerCreateCreated struct {
	/*

	 */
	Location string `json:"Location"`
}

// NewPeerCreateCreated creates PeerCreateCreated with default headers values
func NewPeerCreateCreated() *PeerCreateCreated {

	return &PeerCreateCreated{}
}

// WithLocation adds the location to the peer create created response
func (o *PeerCreateCreated) WithLocation(location string) *PeerCreateCreated {
	o.Location = location
	return o
}

// SetLocation sets the location to the peer create created response
func (o *PeerCreateCreated) SetLocation(location string) {
	o.Location = location
}

// WriteResponse to the client
func (o *PeerCreateCreated) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	// response header Location

	location := o.Location
	if location != "" {
		rw.Header().Set("Location", location)
	}

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(201)
}

// PeerCreateNotFoundCode is the HTTP code returned for type PeerCreateNotFound
const PeerCreateNotFoundCode int = 404

/*PeerCreateNotFound device not found

swagger:response peerCreateNotFound
*/
type PeerCreateNotFound struct {
}

// NewPeerCreateNotFound creates PeerCreateNotFound with default headers values
func NewPeerCreateNotFound() *PeerCreateNotFound {

	return &PeerCreateNotFound{}
}

// WriteResponse to the client
func (o *PeerCreateNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}

/*PeerCreateDefault error

swagger:response peerCreateDefault
*/
type PeerCreateDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewPeerCreateDefault creates PeerCreateDefault with default headers values
func NewPeerCreateDefault(code int) *PeerCreateDefault {
	if code <= 0 {
		code = 500
	}

	return &PeerCreateDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the peer create default response
func (o *PeerCreateDefault) WithStatusCode(code int) *PeerCreateDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the peer create default response
func (o *PeerCreateDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the peer create default response
func (o *PeerCreateDefault) WithPayload(payload *models.Error) *PeerCreateDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the peer create default response
func (o *PeerCreateDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PeerCreateDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
