// Code generated by go-swagger; DO NOT EDIT.

package wireguard

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/suquant/wgrest/models"
)

// PeerListOKCode is the HTTP code returned for type PeerListOK
const PeerListOKCode int = 200

/*PeerListOK ok

swagger:response peerListOK
*/
type PeerListOK struct {

	/*
	  In: Body
	*/
	Payload []*models.WireguardPeer `json:"body,omitempty"`
}

// NewPeerListOK creates PeerListOK with default headers values
func NewPeerListOK() *PeerListOK {

	return &PeerListOK{}
}

// WithPayload adds the payload to the peer list o k response
func (o *PeerListOK) WithPayload(payload []*models.WireguardPeer) *PeerListOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the peer list o k response
func (o *PeerListOK) SetPayload(payload []*models.WireguardPeer) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PeerListOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		// return empty array
		payload = make([]*models.WireguardPeer, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// PeerListNotFoundCode is the HTTP code returned for type PeerListNotFound
const PeerListNotFoundCode int = 404

/*PeerListNotFound not found

swagger:response peerListNotFound
*/
type PeerListNotFound struct {
}

// NewPeerListNotFound creates PeerListNotFound with default headers values
func NewPeerListNotFound() *PeerListNotFound {

	return &PeerListNotFound{}
}

// WriteResponse to the client
func (o *PeerListNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}

/*PeerListDefault error

swagger:response peerListDefault
*/
type PeerListDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewPeerListDefault creates PeerListDefault with default headers values
func NewPeerListDefault(code int) *PeerListDefault {
	if code <= 0 {
		code = 500
	}

	return &PeerListDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the peer list default response
func (o *PeerListDefault) WithStatusCode(code int) *PeerListDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the peer list default response
func (o *PeerListDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the peer list default response
func (o *PeerListDefault) WithPayload(payload *models.Error) *PeerListDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the peer list default response
func (o *PeerListDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PeerListDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
